services:
  scpm:
    build:
      context: .
      args:
        - SCPM_PORT=${SCPM_PORT}
    ports:
      - ${SCPM_PORT}:${SCPM_PORT}
      - 4040:4040
    env_file:
      - .env
    tty: true # for colorized output
