[project]
name = "swarm-checkin-post-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shunsuke KITADA", email = "shunsuke.kitada.0831@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "loguru>=0.7.3",
    "ngrok>=1.4.0",
    "pydantic-settings>=2.10.1",
    "tweepy>=4.16.0",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.0.0",
    "pytest>=6.0.0",
    "ruff>=0.1.5",
]

[tool.uv.build-backend]
module-name = "scpm"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

